graph TD
  SRE[Site Reliability Engineering]

  SRE --> SW[Software Engineering]
  SW --> PL[Programming Languages]
    PL --> SysPL[Systems Programming Languages]
      SysPL --> Rust
      SysPL --> Go
    PL --> ScrPL[Script Programming Languages]
      ScrPL --> Ruby
      ScrPL --> Python
    PL --> FunPL[Functional Programming Languages]
      FunPL --> Haskell
      FunPL --> Lisp

  SW --> PT[Programming Topics]
    PT --> ALG[Algorithms]
      ALG --> SRT[Sorting]
      ALG --> CPX[Complexity]
    PT --> DS[Data Scructures]
      DS --> Graph[Graph]
      DS --> T3[Tree]
      DS --> HS[Hash]

  SW --> DB[Databases]
    DB --> SQL[SQL]
      SQL --> PgSQL[PostgreSQL]
      SQL --> MySQL[MySQL]
    DB --> NoSQL[NoSQL]
      NoSQL --> KV[KeyValue]
        KV --> Rd[Redis]
      NoSQL --> DoS[DocumentStore]
        DoS --> Mng[Mongo]
        DoS --> ES[ElasticSearch]

  SRE --> OPS[Operations]
    OPS --> OS[Operating Systems]
    OPS --> OPSOPS[Operational]
      OPSOPS --> Ter[Terminal]
        Ter --> Bash
        Ter --> PrM[Process Monitoring]
          PrM --> ps
          PrM --> top
          PrM --> htop
          PrM --> atop
          PrM --> lsof
        Ter --> Netw[Network]
          Netw --> dig
          Netw --> iptables
          Netw --> nmap
          Netw --> tcpdump
          Netw --> ping
          Netw --> mtr
          Netw --> traceroute
          Netw --> airmon
          Netw --> airodump

    OPS --> IaC[Infrastructure as Code]
      IaC --> CfgMgt[Configuration Management]
        CfgMgt --> Puppet
        CfgMgt --> Ansible
        CfgMgt --> Chef
      IaC --> Prov[Provisioning]
        Prov --> TF[Terraform]
      IaC --> Orc[Orchestration]
        Orc --> K8S[Kubernetes]
        Orc --> Mesos
        Orc --> Nomad

    OPS --> NET[Networking]
      NET --> NETP[Protocols]
        NETP --> Socket
        NETP --> UDP
        NETP --> TCP
          TCP --> SSH
          TCP --> HTTP
          TCP --> SSL[TLS-SSL]
