graph TD
  SRE[Site Reliability Engineering]

  SRE --> SW[Software Engineering]
  SW --> PL[Programming Languages]
    PL --> SysPL[Systems Programming Languages]
      SysPL --> Rust
      SysPL --> Go
    PL --> ScrPL[Script Programming Languages]
      ScrPL --> Ruby
      ScrPL --> Python
    PL --> FunPL[Functional Programming Languages]
      FunPL --> Haskell
      FunPL --> Lisp
  SW --> PT[Programming Topics]
    PT --> ALG[Algorithms]
      ALG --> SRT[Sorting]
      ALG --> CPX[Complexity]
    PT --> DS[Data Scructures]
      DS --> Graph[Graph]
      DS --> T3[Tree]
      DS --> HS[Hash]
  SW --> DB[Databases]
    DB --> SQL[SQL]
      SQL --> PgSQL[PostgreSQL]
      SQL --> MySQL[MySQL]
    DB --> NoSQL[NoSQL]
      NoSQL --> KV[KeyValue]
        KV --> Rd[Redis]
      NoSQL --> DoS[DocumentStore]
        DoS --> Mng[Mongo]
        DoS --> ES[ElasticSearch]

  SRE --> OPS[Operations]
      OPS --> OS[Operating Systems]
      OPS --> IaC[Infrastructure as Code]
        IaC --> TF[Terraform]
