graph TD
  SRE[Site Reliability Engineering]

  SRE --> SW[Software Engineering]
  SW --> PL[Programming Languages]
    PL --> SysPL[Systems Programming Languages]
      SysPL --> Rust
      SysPL --> Go
    PL --> ScrPL[Script Programming Languages]
      ScrPL --> Ruby
      ScrPL --> Python
    PL --> FunPL[Functional Programming Languages]
      FunPL --> Haskell
      FunPL --> Lisp
